import Image from "next/image";
import Slides from "./_components/Slides";
import CategoryList from "./_components/CategoryList";
import ProductList from "./_components/ProductList";
import Footer from "./_components/Footer";
import GlobaApi from "./_utils/GlobaApi";

export const metadata = {
  title: "Grocery Store",
  description: "Generated by create next app",
};
export default async function Home() {
  const productList = await GlobaApi.getProducts();

  return (
    <main className="px-20">
      <Slides/>
      <CategoryList/>
      <ProductList productList={productList}/>
      <Image src={'/bannerDelivery.png'} alt='banner'
      width={1000} height={400}
      className="w-full h-[400px] object-contain mb-10"/>
      <Footer/>
    </main>
  );
}
